Repository codeigniter4/shield, pull requests merged in 2022-12, with the labels that each got.

#520 refactor: updateActiveDate query builder
  src/Models/UserModel.php
Labels: enhancement

#535 Add filter permission and group
  docs/authorization.md
  docs/install.md
  src/Authorization/AuthorizationException.php
  src/Config/Registrar.php
  src/Exceptions/GroupException.php
  src/Exceptions/PermissionException.php
  src/Filters/AbstractAuthFilter.php
  src/Filters/GroupFilter.php
  src/Filters/PermissionFilter.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/sk/Auth.php
  src/Language/tr/Auth.php
  tests/Authentication/Filters/AbstractFilterTest.php
  tests/Authentication/Filters/GroupFilterTest.php
  tests/Authentication/Filters/PermissionFilterTest.php
Labels: enhancement

#560 chore: update rector.php
  .github/workflows/rector.yml
  .php-cs-fixer.dist.php
  rector.php
  tests/Authentication/AuthenticationTest.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
  tests/Authentication/Filters/AbstractFilterTest.php
  tests/Authentication/HasAccessTokensTest.php
  tests/Authorization/AuthorizableTest.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Unit/CompositionValidatorTest.php
  tests/Unit/DictionaryValidatorTest.php
  tests/Unit/FilterInCliTest.php
  tests/Unit/NothingPersonalValidatorTest.php
  tests/Unit/PwnedValidatorTest.php
Labels: github_actions

#564 chore: update GA cache
  .github/workflows/phpcsfixer.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit-lang.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/rector.yml
  .github/workflows/unused.yml
Labels: github_actions

#565 dev: Allow easier overriding of views in developer applications.
  docs/customization.md
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Controllers/RegisterController.php
  src/Traits/Viewable.php
Labels: enhancement

#570 docs: add configuration for Config\Email
  docs/install.md
  docs/quickstart.md
Labels: documentation
