Repository codeigniter4/shield, pull requests merged in 2022-06, with the labels that each got.

#204 fix: display message magic link controller if email not send
  src/Controllers/MagicLinkController.php
  src/Language/en/Auth.php
  src/Language/fa/Auth.php
  src/Language/ja/Auth.php
Labels: bug

#211 fix: Debugbar error after logout
  src/Authentication/Authenticators/Session.php
  tests/Collectors/AuthTest.php
Labels: bug

#213 feat: add message after successful logout
  src/Controllers/LoginController.php
  src/Language/en/Auth.php
  src/Language/fa/Auth.php
  src/Language/ja/Auth.php
  src/Views/login.php
  tests/Controllers/LoginTest.php
Labels: enhancement

#198 chore: update rector to ^0.13.3
  .github/workflows/rector.yml
  src/Controllers/LoginController.php
  tests/Unit/PwnedValidatorTest.php
Labels: github_actions

#212 fix: RememberMe cookie does not work with Cookie prefix
  src/Authentication/Authenticators/Session.php
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Labels: bug

#222 fix: error occurs if a user deleted from the database has session User Info or RememberMe cookie
  src/Authentication/Authenticators/Session.php
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Labels: bug

#220 fix: `use` is missing in the replaced source files
  src/Commands/Setup.php
  tests/Commands/SetupTest.php
Labels: bug

#231 fix: `Session::logout()` does not work
  src/Authentication/Authenticators/Session.php
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Labels: bug

#232 fix: workaround for email only registration/login
  src/Authentication/Passwords/NothingPersonalValidator.php
  src/Controllers/RegisterController.php
  src/Models/UserModel.php
  tests/Unit/NothingPersonalValidatorTest.php
Labels: bug

#241 docs: improve installation
  docs/0 - install.md
Labels: documentation

#238 fix: datetime for defaultLocale set fa
  src/Authentication/Authenticators/AccessTokens.php
  src/Authorization/Traits/Authorizable.php
  src/Controllers/MagicLinkController.php
  src/Models/LoginModel.php
  src/Models/TokenLoginModel.php
  tests/Authorization/AuthorizableTest.php
Labels: bug
