Repository codeigniter4/shield, pull requests merged in 2022-07, with the labels that each got.

#274 chore: add language unit tests
  .github/workflows/phpunit-lang.yml
  phpunit.xml.dist
Labels: github_actions

#282 docs: remove incorrect description in authorization.md
  docs/authorization.md
Labels: documentation

#297 fix: shield:setup adds routes in wrong location
  src/Commands/Setup.php
  tests/Commands/Setup/ContentReplacerTest.php
Labels: bug

#275 fix: UserModel::save() can't update User's email/password
  docs/quickstart.md
  src/Controllers/RegisterController.php
  src/Entities/User.php
  src/Exceptions/ValidationException.php
  src/Models/CheckQueryReturnTrait.php
  src/Models/UserModel.php
  tests/Unit/LoginModelTest.php
  tests/Unit/UserModelTest.php
Labels: bug

#310 feat: add user permissions to debug-toolbar
  src/Collectors/Auth.php
  src/Config/Auth.php
  tests/Collectors/AuthTest.php
Labels: enhancement

#308 fix: UserModel::findById() does not work with withIdentities()
  src/Models/UserModel.php
  tests/Unit/UserTest.php
Labels: bug

#301 Add previousLogin method
  src/Entities/User.php
  src/Models/LoginModel.php
  tests/Unit/UserTest.php
Labels: enhancement
