Repository codeigniter4/shield, pull requests merged in 2022-09, with the labels that each got.

#416 refactor: fix PHPStan error
  src/Auth.php
  src/Config/Auth.php
  src/Entities/Entity.php
  src/Entities/User.php
  src/Entities/UserIdentity.php
  src/Models/UserModel.php
  src/Result.php
Labels: refactor

#421 Minor fix for docs
  docs/authentication.md
  docs/quickstart.md
Labels: documentation

#417 ApiToken docs and filter update.
  docs/guides/api-tokens.md
  docs/index.md
  src/Filters/TokenAuth.php
  tests/Authentication/Filters/AbstractFilterTest.php
  tests/Authentication/Filters/TokenFilterTest.php
Labels: documentation, enhancement

#425 fix: NothingPersonalValidator strip_explode too sensible
  src/Authentication/Passwords/NothingPersonalValidator.php
  tests/Unit/NothingPersonalValidatorTest.php
Labels: bug

#413 feat: notify devs when user has used magic link login.
  docs/events.md
  docs/quickstart.md
  docs/session_auth_event_and_logging.md
  src/Controllers/MagicLinkController.php
  tests/Authentication/MagicLinkTest.php
Labels: enhancement

#432 docs: Missing apostrophe
  docs/guides/api-tokens.md
Labels: documentation

#428 docs: rename file `api-tokens.md` to `api_tokens.md`
  docs/guides/api_tokens.md
  docs/index.md
Labels: documentation

#429 docs: explanation of how to use the `session` filter to protect pages
  docs/install.md
Labels: documentation

#427 docs: add some important shield features to `README.md`
  README.md
Labels: documentation

#422 docs: mobile token guides
  docs/guides/mobile_apps.md
  docs/index.md
Labels: documentation

#437 docs: add semi colon
  docs/guides/mobile_apps.md
Labels: documentation

#443 docs: fix protect all url with `$globals`
  docs/install.md
Labels: documentation

#445 docs: replace `reason` to `reason()`
  docs/guides/mobile_apps.md
Labels: documentation

#442 fix: correct display of the error in case of change `authenticatorHeader`
  docs/guides/api_tokens.md
  docs/guides/mobile_apps.md
  src/Authentication/Authenticators/AccessTokens.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/ja/Auth.php
  src/Language/sk/Auth.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
Labels: bug

#449 docs: add note about strong_password
  docs/concepts.md
Labels: documentation

#452 fix: bug that when UserIdentity is changed, the correct user identities are not returned afterwards
  src/Entities/User.php
  src/Entities/UserIdentity.php
  src/Models/UserIdentityModel.php
  src/Models/UserModel.php
  tests/Unit/UserModelTest.php
  tests/Unit/UserTest.php
Labels: bug

#436 docs: fixed typo in `guides/mobile_apps.md`
  docs/guides/mobile_apps.md
Labels: documentation
