Repository codeigniter4/shield, pull requests merged in 2022-11, with the labels that each got.

#502 chore: update GA deptrac.yml
  .github/workflows/deptrac.yml
Labels: github_actions

#498 fix: remove `username` in $validFields by default
  src/Config/Auth.php
  src/Controllers/RegisterController.php
  tests/Controllers/LoginTest.php
Labels: bug

#504 fix: UserModel cannot save an array
  src/Models/UserModel.php
  tests/Unit/UserModelTest.php
Labels: bug

#510 fix: TypeError when checking invalid permission
  src/Authorization/Traits/Authorizable.php
  tests/Authorization/AuthorizableTest.php
Labels: bug

#501 fix: set only validated fields to User Entity in RegisterController
  src/Controllers/RegisterController.php
Labels: bug

#431 feat: add request info to all emails
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Controllers/MagicLinkController.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/ja/Auth.php
  src/Language/sk/Auth.php
  src/Views/Email/email_2fa_email.php
  src/Views/Email/email_activate_email.php
  src/Views/Email/magic_link_email.php
  tests/Controllers/ActionsTest.php
Labels: enhancement

#514 fix: withIdentities() when user not exists
  src/Models/UserModel.php
  tests/Unit/UserTest.php
Labels: bug

#513 MkDocs Documentation
  .github/workflows/docs.yml
  .gitignore
  docs/assets/favicon.ico
  docs/assets/flame.svg
  docs/assets/hljs.js
  docs/concepts.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#523 docs: add code block language for fix website
  README.md
  docs/install.md
Labels: documentation

#528 docs: fix property notation
  docs/concepts.md
Labels: documentation

#527 fix: minimum password length check
  src/Authentication/Passwords/CompositionValidator.php
  tests/Unit/CompositionValidatorTest.php
Labels: bug

#507 Fix comments for $groups in AuthGroups.php
  src/Config/AuthGroups.php
Labels: waiting for info

#540 refactor: use `::class` constants
  docs/auth_actions.md
  docs/concepts.md
  docs/quickstart.md
  src/Config/Auth.php
Labels: refactor

#548 fix: findByCredentials() returns User when email is empty string
  src/Models/UserModel.php
  tests/Unit/UserModelTest.php
Labels: bug

#549 feat: add Turkish lang file
  src/Language/tr/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/TurkishTranslationTest.php
Labels: lang
