Repository codeigniter4/shield, pull requests merged in 2022-08, with the labels that each got.

#338 fix: Session::refreshRememberMeToken() not update row in database
  src/Authentication/Authenticators/Session.php
Labels: bug

#339 fix: PostgreSQL tests
  src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
  src/Entities/Cast/IntBoolCast.php
  src/Entities/Entity.php
  src/Entities/Login.php
  src/Entities/User.php
  src/Entities/UserIdentity.php
  src/Models/CheckQueryReturnTrait.php
  tests/Controllers/LoginTest.php
  tests/Unit/UserModelTest.php
  tests/Unit/UserTest.php
Labels: bug

#350 fix: field name translation in validation errors
  docs/customization.md
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Controllers/RegisterController.php
Labels: bug

#347 Change the second param in Forge's `createTable()` method
  src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
Labels: refactor

#356 docs: remove unnecessary details of `CI4.1.x`
  docs/install.md
Labels: documentation

#345 Fix email deliverability error log
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Controllers/MagicLinkController.php
Labels: enhancement

#353 Load an auth helper in ActionController
  src/Controllers/ActionController.php
Labels: bug

#362 refactor: add intermediate variable and specify type in TokenAuth
  src/Filters/TokenAuth.php
  tests/Authentication/AuthTest.php
Labels: refactor

#361 refactor: remove unused Auth::$views items
  src/Config/Auth.php
Labels: refactor

#363 docs: link custom validation rules & add custom rules for login
  docs/customization.md
Labels: documentation

#366 fix: bootstrap column on mobile device
  src/Views/email_2fa_show.php
  src/Views/email_2fa_verify.php
  src/Views/email_activate_show.php
Labels: bug

#351 fix: show validate errors in `magic-link`
  src/Controllers/MagicLinkController.php
  src/Views/magic_link_form.php
  tests/Authentication/MagicLinkTest.php
  tests/Controllers/MagicLinkTest.php
Labels: enhancement

#369 refactor: moving email tpl to `src/Views/Email/`
  docs/auth_actions.md
  src/Config/Auth.php
  src/Views/Email/email_2fa_email.php
  src/Views/Email/email_activate_email.php
  src/Views/Email/magic_link_email.php
Labels: refactor

#370 Spanish (Spain) translation
  src/Language/es/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/SpanishTranslationTest.php
Labels: enhancement, lang

#368 feat: autoload helpers by Composer
  composer.json
  docs/authentication.md
  docs/install.md
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Commands/Setup.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Entities/AccessToken.php
  src/Filters/ChainAuth.php
  src/Filters/SessionAuth.php
  src/Filters/TokenAuth.php
  src/Test/AuthenticationTesting.php
  tests/Authentication/AuthHelperTest.php
  tests/Authentication/MagicLinkTest.php
  tests/Controllers/ActionsTest.php
  tests/Controllers/LoginTest.php
  tests/Controllers/MagicLinkTest.php
  tests/Controllers/RegisterTest.php
Labels: refactor

#371 Improve setup
  docs/install.md
  src/Commands/Setup.php
Labels: enhancement

#376 fix: AccessTokens throws DataException
  src/Authentication/Authenticators/AccessTokens.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
Labels: bug

#377 refactor: add return types
  .php-cs-fixer.dist.php
  src/Authentication/Actions/EmailActivator.php
  src/Authentication/Authenticators/Session.php
  src/Commands/Setup.php
  src/Filters/AuthRates.php
  src/Filters/ChainAuth.php
  src/Filters/SessionAuth.php
  src/Filters/TokenAuth.php
  src/Models/UserIdentityModel.php
  src/Models/UserModel.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
  tests/Controllers/MagicLinkTest.php
  tests/Unit/NothingPersonalValidatorTest.php
Labels: refactor

#384 feat: update `shield:setup` for Security Setup
  docs/install.md
  src/Commands/Setup.php
  tests/Commands/SetupTest.php
Labels: enhancement

#392 Refactor record active date
  src/Authentication/Authenticators/AccessTokens.php
  src/Authentication/Authenticators/Session.php
  src/Models/UserModel.php
  tests/Authentication/Filters/SessionFilterTest.php
  tests/Authentication/Filters/TokenFilterTest.php
Labels: refactor

#383 fix: redirect()->withInput() causes ValidationException
  src/Models/CheckQueryReturnTrait.php
Labels: bug

#398 refactor: TokenAuth
  src/Filters/TokenAuth.php
Labels: refactor

#391 fix: Session auth action checks
  src/Authentication/Authenticators/Session.php
  src/Controllers/LoginController.php
  src/Controllers/RegisterController.php
  tests/Controllers/RegisterTest.php
Labels: bug

#401 docs: improve install.md
  docs/install.md
Labels: documentation

#397 refactor: Auth Actions (action classes are executed in the order set in `Config/Auth::$actions`)
  docs/auth_actions.md
  docs/quickstart.md
  src/Authentication/Actions/ActionInterface.php
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Authentication/Authenticators/Session.php
  src/Config/Auth.php
  src/Models/UserIdentityModel.php
  tests/Unit/EmailActivatorTest.php
Labels: refactor

#403 docs: change section order in quickstart.md
  docs/quickstart.md
Labels: documentation

#404 fix: correctly record the datetime for `last_active`
  src/Models/UserModel.php
Labels: bug

#409 fix: add logic to skip filters if not in HTTP
  src/Filters/AuthRates.php
  src/Filters/ChainAuth.php
  src/Filters/SessionAuth.php
  src/Filters/TokenAuth.php
  tests/Unit/FilterInCliTest.php
Labels: bug

#410 docs: fix `revokeAllAccessTokens()` sample code
  docs/authentication.md
Labels: documentation

#402 feat: support other databases
  src/Entities/AccessToken.php
  src/Entities/UserIdentity.php
  src/Models/LoginModel.php
  src/Models/UserModel.php
Labels: enhancement

#331 chore: add multiple db platforms in GA workflow PHPUnit
  .github/workflows/phpunit.yml
  tests/_support/Config/Registrar.php
Labels: github_actions

#414 docs: add Session Authenticator Event and Logging
  docs/events.md
  docs/session_auth_event_and_logging.md
Labels: documentation
