Repository codeigniter4/shield, pull requests merged in 2022-10, with the labels that each got.

#457 docs: fix namespace for `BaseController`
  docs/guides/mobile_apps.md
Labels: documentation

#460 refactor: remove double instance of `auth('session')`
  src/Controllers/LoginController.php
Labels: refactor

#458 refactor: remove unnecessary auth helper of `ActionController`
  src/Controllers/ActionController.php
Labels: refactor

#462 bug: fix magic_link_message view template
  src/Views/magic_link_message.php
Labels: bug

#466 docs: fixed typo in `docs/install.md`
  docs/install.md
Labels: documentation

#488 docs: add `auth/a/*` to except list
  docs/install.md
Labels: documentation
