Repository codeigniter4/shield, pull requests merged in 2023-05, with the labels that each got.

#724 lang: [lt] add Lithuanian localization
  src/Language/lt/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/LithuanianTranslationTest.php
Labels: lang

#728 fix: typo in `getMaxLengthRule()` method name
  src/Authentication/Passwords.php
  src/Controllers/LoginController.php
  src/Controllers/RegisterController.php
Labels: refactor

#743 docs: fix sample code in authorization.md
  docs/authorization.md
Labels: documentation

#730 feat: add login link to magic link form view
  src/Language/bg/Auth.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/lt/Auth.php
  src/Language/pt-BR/Auth.php
  src/Language/pt/Auth.php
  src/Language/sk/Auth.php
  src/Language/sr/Auth.php
  src/Language/sv-SE/Auth.php
  src/Language/tr/Auth.php
  src/Language/uk/Auth.php
  src/Views/magic_link_form.php
  tests/Controllers/MagicLinkTest.php
Labels: enhancement

#745 feat: Add InnoDB engine to migration create table methods
  src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
Labels: enhancement

#742 fix: simplify extraction of email parts
  src/Authentication/Passwords/NothingPersonalValidator.php
Labels: bug, refactor

#744 feat: add 'DBGroup' for customization db group
  docs/addons/jwt.md
  docs/guides/mobile_apps.md
  src/Config/Auth.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Controllers/RegisterController.php
  src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
  src/Models/BaseModel.php
Labels: new feature, tests needed

#748 refactor: use ::class keyword in config()
  src/Auth.php
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Authentication/Authenticators/AccessTokens.php
  src/Authentication/Authenticators/Session.php
  src/Authentication/Passwords.php
  src/Authentication/Passwords/ValidationRules.php
  src/Authorization/Traits/Authorizable.php
  src/Config/Services.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Controllers/RegisterController.php
  src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
  src/Filters/ChainAuth.php
  src/Filters/ForcePasswordResetFilter.php
  src/Filters/SessionAuth.php
  src/Views/email_2fa_show.php
  src/Views/email_2fa_verify.php
  src/Views/email_activate_show.php
  src/Views/login.php
  src/Views/magic_link_form.php
  src/Views/magic_link_message.php
  src/Views/register.php
Labels: refactor

#747 fix: add support for all request types when building a user from request.
  docs/guides/strengthen_password.md
  src/Authentication/Passwords/ValidationRules.php
  src/Controllers/RegisterController.php
Labels: enhancement
