Repository codeigniter4/shield, pull requests merged in 2023-12, with the labels that each got.

#969 test: update assertion in JWTManagerTest
  tests/Unit/Authentication/JWT/JWTManagerTest.php
Labels: testing

#977 docs: add explanations to "Adding Attributes to Users"
  docs/customization/adding_attributes_to_users.md
  docs/customization/user_provider.md
Labels: documentation

#976 refactor: remove supportOldDangerousPassword
  UPGRADING.md
  phpstan-baseline.php
  src/Authentication/Authenticators/Session.php
  src/Authentication/Passwords.php
  src/Config/Auth.php
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Labels: breaking change, refactor

#983 docs: Remove emojis from index
  docs/index.md
Labels: documentation

#985 Allow specifying namespace when generating routes.
  docs/customization/route_config.md
  src/Auth.php
  tests/Unit/AuthRoutesTest.php
Labels: enhancement
