Repository codeigniter4/shield, pull requests merged in 2023-10, with the labels that each got.

#868 fix: Change the visibility of validation properties for easier inheritance
  src/Validation/ValidationRules.php
Labels: enhancement

#870 docs: remove `Config\Security::$csrfProtection` config method by `.env`
  docs/getting_started/install.md
Labels: documentation

#873 docs: update sample LoginController for JWT
  docs/addons/jwt.md
Labels: documentation

#872 refactor: remove Composer autoloading of email helper
  composer.json
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Controllers/MagicLinkController.php
Labels: refactor

#871 refactor: update minimum CI4 version to 4.3.5
  README.md
  UPGRADING.md
  composer.json
  docs/getting_started/install.md
  src/Test/MockInputOutput.php
  tests/Commands/SetupTest.php
  tests/Commands/UserModelGeneratorTest.php
  tests/Controllers/LoginTest.php
Labels: refactor

#875 docs: improve home
  docs/index.md
Labels: documentation

#877 refactor: remove outdated code for CI 4.2 or before
  src/Commands/Generators/UserModelGenerator.php
  src/Models/CheckQueryReturnTrait.php
Labels: refactor

#878 test: fix UserTest assertions for Windows
  tests/Commands/UserTest.php
Labels: testing

#876 feat: `shield:setup` does Email setup
  docs/getting_started/install.md
  rector.php
  src/Commands/BaseCommand.php
  src/Commands/Setup.php
  src/Commands/User.php
  src/Commands/Utils/InputOutput.php
  src/Test/MockInputOutput.php
  tests/Commands/SetupTest.php
Labels: enhancement

#883 fix: use named routes for redirects and form submission
  src/Controllers/RegisterController.php
  src/Views/email_activate_show.php
Labels: bug

#884 docs: add how to use locale routes
  docs/customization/route_config.md
Labels: documentation

#891 [Rector] Apply StringifyStrNeedlesRector
  rector.php
  src/Authentication/Passwords/NothingPersonalValidator.php
  src/Authentication/Passwords/PwnedValidator.php
Labels: refactor

#892 chore: fix no-merge-commits.yml
  .github/workflows/no-merge-commits.yml
Labels: github_actions

#895 docs: improve instructions for Customizing Login Identifier
  docs/customization/login_identifier.md
Labels: documentation

#897 docs: small fixes for Customizing Login Identifier
  docs/customization/login_identifier.md
Labels: documentation

#894 refactor: replace `/>` with `>` for input tags
  src/Views/email_2fa_show.php
  src/Views/email_2fa_verify.php
  src/Views/email_activate_show.php
  src/Views/login.php
  src/Views/magic_link_form.php
  src/Views/register.php
Labels: refactor

#896 docs: add "Customizing Views"
  docs/customization/views.md
  mkdocs.yml
Labels: documentation

#903 docs: fix small items
  docs/addons/jwt.md
  docs/customization/integrating_custom_view_libs.md
  docs/getting_started/concepts.md
  docs/guides/mobile_apps.md
  docs/references/authentication/authentication.md
  docs/references/events.md
Labels: documentation

#901 test: update Config\Registrar
  phpstan-baseline.php
  tests/_support/Config/Registrar.php
Labels: refactor

#893 refactor: remove Composer autoloading of auth helper
  UPGRADING.md
  composer.json
  docs/getting_started/install.md
  docs/references/authentication/authentication.md
  src/Authentication/Authenticators/Session.php
  src/Authorization/Groups.php
  src/Authorization/Traits/Authorizable.php
  src/Commands/Setup.php
  src/Controllers/ActionController.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Controllers/RegisterController.php
  src/Filters/ForcePasswordResetFilter.php
  src/Filters/HmacAuth.php
  src/Filters/JWTAuth.php
  src/Filters/SessionAuth.php
  src/Filters/TokenAuth.php
  src/Helpers/email_helper.php
  src/Validation/ValidationRules.php
  tests/Commands/SetupTest.php
  tests/_support/TestCase.php
Labels: breaking change, refactor

#906 docs: add note for removing email from registration in customization/login_identifier
  docs/customization/login_identifier.md
Labels: documentation

#907 docs: add "Adding Attributes to Users"
  docs/customization/adding_attributes_to_users.md
  mkdocs.yml
Labels: documentation

#911 fix date localized-plugin and refactor action
  .github/workflows/docs.yml
Labels: documentation, github_actions

#913 lang: [id] add translation
  src/Language/id/Auth.php
  tests/Language/IndonesianTranslationTest.php
Labels: lang

#790 feat: add redirect denied for filter
  UPGRADING.md
  src/Config/Auth.php
  src/Filters/AbstractAuthFilter.php
  src/Filters/GroupFilter.php
  src/Filters/PermissionFilter.php
  tests/Authentication/Filters/GroupFilterTest.php
  tests/Authentication/Filters/PermissionFilterTest.php
Labels: enhancement, breaking change

#916 refactor: update default value `$hashCost` to 12
  src/Config/Auth.php
  tests/Unit/PasswordsTest.php
Labels: refactor

#915 fix: replace `url_is()`
  src/Filters/AbstractAuthFilter.php
  src/Filters/SessionAuth.php
Labels: bug

#917 docs: remove unneeded `/` from routes
  docs/guides/api_hmac_keys.md
  docs/guides/api_tokens.md
Labels: documentation

#919 docs: fix email rule for mobileLogin
  docs/guides/mobile_apps.md
Labels: documentation

#921 docs: add `logout` to session except list
  docs/customization/route_config.md
  docs/quick_start_guide/using_session_auth.md
  docs/references/controller_filters.md
Labels: documentation

#908 perf: refactor Auth
  phpstan-baseline.php
  src/Auth.php
  src/Authentication/Authentication.php
  src/Config/Services.php
  src/Helpers/auth_helper.php
Labels: breaking change, refactor

#927 test: refactor SessionFilterTest by rector 0.18.6
  tests/Authentication/Filters/SessionFilterTest.php
Labels: refactor, testing

#931 docs: improve on filter aliases
  docs/quick_start_guide/using_session_auth.md
  docs/references/controller_filters.md
Labels: documentation

#935 lang: [uk] Adjust translations for uk/Auth.php
  src/Language/uk/Auth.php
Labels: lang

#936 lang: [ru] add Russian language
  src/Language/ru/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/RussianTranslationTest.php
Labels: lang
