Repository codeigniter4/shield, pull requests merged in 2023-09, with the labels that each got.

#806 fix: UserModel::assignIdentities() always produces a DB query
  phpstan.neon.dist
  src/Entities/User.php
  src/Models/UserModel.php
  tests/Unit/UserTest.php
Labels: bug

#810 lang: [ar] update arabic translate
  src/Language/ar/Auth.php
Labels: lang

#799 fix: unauthorized users for groups and permissions are not redirected to the previous url
  src/Filters/AbstractAuthFilter.php
  tests/Authentication/Filters/GroupFilterTest.php
  tests/Authentication/Filters/PermissionFilterTest.php
Labels: bug

#812 chore: add new GitHub action for smart commenting
  .github/workflows/smart_commenting.yml
Labels: github_actions

#811 chore: use workflows in codeigniter4/.github
  .github/workflows/deptrac.yml
  .github/workflows/phpcsfixer.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/rector.yml
  .github/workflows/unused.yml
  composer.json
  rector.php
  tests/Controllers/ActionsTest.php
  tests/Unit/PwnedValidatorTest.php
Labels: github_actions

#821 chore: fix workflow filename
  .github/workflows/smart-commenting.yml
Labels: github_actions

#819 docs: fix filename in README
  README.md
Labels: documentation

#827 chore: fix workflow on section
  .github/workflows/deptrac.yml
  .github/workflows/phpcsfixer.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/rector.yml
  .github/workflows/unused.yml
Labels: github_actions

#825 fix: property $table visibility in RegisterController
  src/Controllers/RegisterController.php
Labels: bug

#829 fix: cannot register when you remove email from `$validFields`
  src/Authentication/Passwords/ValidationRules.php
  tests/Controllers/RegisterTest.php
Labels: bug

#795 feat: HMAC SHA256 Authentication
  .github/workflows/phpcpd.yml
  README.md
  composer.json
  docs/authentication.md
  docs/guides/api_hmac_keys.md
  docs/install.md
  mkdocs.yml
  src/Authentication/Authenticators/HmacSha256.php
  src/Authentication/Traits/HasHmacTokens.php
  src/Commands/Setup.php
  src/Config/Auth.php
  src/Config/AuthToken.php
  src/Config/Registrar.php
  src/Entities/User.php
  src/Filters/HmacAuth.php
  src/Models/UserIdentityModel.php
  src/Result.php
  tests/Authentication/Authenticators/HmacAuthenticatorTest.php
  tests/Authentication/Filters/HmacFilterTest.php
  tests/Authentication/HasHmacTokensTest.php
  tests/Commands/SetupTest.php
Labels: new feature

#839 docs: reorganize (part 1)
  docs/auth_actions.md
  docs/authentication.md
  docs/authorization.md
  docs/concepts.md
  docs/customization.md
  docs/customization/extending_controllers.md
  docs/customization/integrating_custom_view_libs.md
  docs/customization/login_identifier.md
  docs/customization/redirect_urls.md
  docs/customization/route_config.md
  docs/customization/table_names.md
  docs/customization/user_provider.md
  docs/customization/validation_rules.md
  docs/events.md
  docs/guides/banning_users.md
  docs/guides/forcing_password_reset.md
  docs/guides/strengthen_password.md
  docs/index.md
  docs/install.md
  docs/quick_start_guide/authentication_flow.md
  docs/quick_start_guide/authorization_flow.md
  docs/quick_start_guide/managing_users.md
  docs/quickstart.md
  docs/testing.md
  mkdocs.yml
Labels: documentation

#844 fix: [HMAC Auth] wrong header key
  src/Authentication/Authenticators/HmacSha256.php
Labels: bug

#833 feat: add CLI command to manage users
  rector.php
  src/Commands/Exceptions/BadInputException.php
  src/Commands/Exceptions/CancelException.php
  src/Commands/User.php
  src/Commands/Utils/InputOutput.php
  src/Controllers/RegisterController.php
  src/Exceptions/UserNotFoundException.php
  src/Test/MockInputOutput.php
  src/Validation/RegistrationValidationRules.php
  tests/Commands/UserTest.php
Labels: new feature

#843 fix: AccessTokens authenticator records all accesses to database
  UPGRADING.md
  src/Authentication/Authenticators/AccessTokens.php
  src/Config/AuthToken.php
  src/Filters/TokenAuth.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
Labels: bug

#841 docs: reorganize (part 2)
  docs/customization/integrating_custom_view_libs.md
  docs/customization/route_config.md
  docs/customization/table_names.md
  docs/customization/user_provider.md
  docs/customization/validation_rules.md
  docs/getting_started/authenticators.md
  docs/getting_started/concepts.md
  docs/getting_started/configuration.md
  docs/getting_started/install.md
  docs/guides/api_tokens.md
  docs/index.md
  docs/install.md
  docs/quick_start_guide/using_authorization.md
  docs/quick_start_guide/using_session_auth.md
  docs/references/auth_actions.md
  docs/references/authentication.md
  docs/references/authorization.md
  docs/references/controller_filters.md
  docs/references/events.md
  docs/references/magic_link_login.md
  docs/references/session_auth_event_and_logging.md
  docs/references/testing.md
  docs/user_management/banning_users.md
  docs/user_management/forcing_password_reset.md
  docs/user_management/managing_users.md
  mkdocs.yml
Labels: documentation

#813 chore: use codeigniter4/.github/.github/workflows/phpcpd.yml
  .github/workflows/phpcpd.yml
Labels: github_actions

#847 docs: reorganize (part 3/3)
  docs/getting_started/authenticators.md
  docs/references/authentication.md
  docs/references/authentication/auth_actions.md
  docs/references/authentication/authentication.md
  docs/references/authentication/hmac.md
  docs/references/authentication/session.md
  docs/references/authentication/tokens.md
  docs/references/authorization.md
  docs/references/events.md
  docs/references/session_auth_event_and_logging.md
  mkdocs.yml
Labels: documentation

#848 docs: add about `shield:user` command
  docs/user_management/managing_users.md
Labels: documentation

#854 lang: [ar] fix issue #851
  src/Language/ar/Auth.php
Labels: lang

#852 docs: update validation rules
  docs/customization/validation_rules.md
Labels: documentation

#845 refactor: move config items
  UPGRADING.md
  docs/addons/jwt.md
  docs/getting_started/configuration.md
  docs/guides/api_hmac_keys.md
  docs/guides/api_tokens.md
  docs/guides/mobile_apps.md
  docs/references/authentication/hmac.md
  docs/references/authentication/tokens.md
  src/Authentication/Authenticators/AccessTokens.php
  src/Authentication/Authenticators/HmacSha256.php
  src/Config/Auth.php
  src/Config/AuthSession.php
  src/Config/AuthToken.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Validation/RegistrationValidationRules.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
  tests/Authentication/Authenticators/HmacAuthenticatorTest.php
  tests/Controllers/LoginTest.php
Labels: breaking change, refactor

#856 docs: remove space from code
  docs/addons/jwt.md
  docs/references/authentication/auth_actions.md
  docs/references/authorization.md
Labels: documentation

#858 feat: added `revokeAccessTokenBySecret()`
  docs/guides/api_tokens.md
  docs/references/authentication/tokens.md
  src/Authentication/Traits/HasAccessTokens.php
  src/Models/UserIdentityModel.php
  tests/Authentication/HasAccessTokensTest.php
Labels: enhancement

#864 docs: change dotenv to text
  docs/addons/jwt.md
Labels: documentation

#863 chore: fix phpunit workflow
  .github/workflows/phpunit-lowest.yml
Labels: github_actions

#861 refactor: validation rules
  docs/customization/validation_rules.md
  src/Commands/User.php
  src/Config/Auth.php
  src/Controllers/LoginController.php
  src/Controllers/MagicLinkController.php
  src/Controllers/RegisterController.php
  src/Validation/RegistrationValidationRules.php
  src/Validation/ValidationRules.php
Labels: refactor
