Repository codeigniter4/shield, pull requests merged in 2023-01, with the labels that each got.

#582 docs: improve installation instruction
  docs/install.md
Labels: documentation

#558 feat: add `shield:model` command
  docs/concepts.md
  src/Commands/Generators/UserModelGenerator.php
  src/Commands/Generators/Views/usermodel.tpl.php
  src/Config/Registrar.php
  tests/Commands/UserModelGeneratorTest.php
Labels: enhancement

#576 bug: Call to a member function inGroup() on null after logging out
  src/Controllers/LoginController.php
Labels: bug

#588 refactor: remove unused `Auth::class`
  src/Filters/AuthRates.php
  src/Filters/ChainAuth.php
Labels: refactor

#577 Fix: Unnamed Auth routes returns an error when inside a route group
  docs/customization.md
  docs/install.md
  src/Config/Auth.php
  src/Config/AuthRoutes.php
Labels: enhancement

#594 fix: update `shield:setup` for correct run in CI4.3.0+
  src/Commands/Setup.php
  tests/Commands/SetupTest.php
Labels: bug

#599 chore: update phpunit.yml
  .github/workflows/phpunit.yml
  composer.json
Labels: github_actions

#589 Fix: groups and permissions filter redirects
  src/Filters/AbstractAuthFilter.php
  tests/Authentication/Filters/GroupFilterTest.php
  tests/Authentication/Filters/PermissionFilterTest.php
Labels: bug

#602 Replace deprecated `COMPOSER_TOKEN` with `GITHUB_TOKEN`
  .github/workflows/deptrac.yml
  .github/workflows/phpcsfixer.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit-lang.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/rector.yml
  .github/workflows/unused.yml
Labels: github_actions

#603 docs: improve quickstart.md and customization.md
  docs/customization.md
  docs/quickstart.md
Labels: documentation

#604 docs: improve User Provider
  docs/concepts.md
  docs/customization.md
Labels: documentation

#605 docs: make file paths bold
  docs/authentication.md
  docs/authorization.md
  docs/events.md
  docs/guides/api_tokens.md
  docs/guides/mobile_apps.md
  docs/install.md
Labels: documentation

#606 docs: remove unsupported Filter code sample
  docs/authorization.md
Labels: documentation
