Repository codeigniter4/shield, pull requests merged in 2023-08, with the labels that each got.

#776 docs: fix example code of extending controller
  docs/customization.md
Labels: documentation

#780 lang: [ar] Arabic translate
  src/Language/ar/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/ArabicTranslationTest.php
Labels: lang

#778 fix: Magic Link Login can be used even if `$allowMagicLinkLogins` is false
  src/Controllers/MagicLinkController.php
  src/Language/ar/Auth.php
  src/Language/bg/Auth.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/lt/Auth.php
  src/Language/pt-BR/Auth.php
  src/Language/pt/Auth.php
  src/Language/sk/Auth.php
  src/Language/sr/Auth.php
  src/Language/sv-SE/Auth.php
  src/Language/tr/Auth.php
  src/Language/uk/Auth.php
  tests/Controllers/MagicLinkTest.php
Labels: bug

#784 lang: [sk] translate missing slovak sentences
  src/Language/sk/Auth.php
Labels: lang

#785 lang: [ar] translating missed
  src/Language/ar/Auth.php
Labels: lang

#782 docs: update RELEASE.md
  admin/RELEASE.md
Labels: documentation

#791 feat: add support for multiple permissions check for users
  docs/authorization.md
  src/Authorization/Traits/Authorizable.php
  tests/Authorization/AuthorizableTest.php
Labels: enhancement

#793 feat: redirect after login to entrance url
  src/Config/Auth.php
  src/Filters/SessionAuth.php
  tests/Authentication/Filters/SessionFilterTest.php
Labels: enhancement

#796 fix: use short classname for config()
  src/Authentication/Authenticators/JWT.php
  src/Authentication/JWT/Adapters/FirebaseAdapter.php
  src/Authentication/JWT/JWSEncoder.php
  src/Filters/JWTAuth.php
  src/Models/BaseModel.php
Labels: bug

#801 feat: improve user experience in forms
  src/Language/ar/Auth.php
  src/Language/bg/Auth.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/lt/Auth.php
  src/Language/pt-BR/Auth.php
  src/Language/pt/Auth.php
  src/Language/sk/Auth.php
  src/Language/sr/Auth.php
  src/Language/sv-SE/Auth.php
  src/Language/tr/Auth.php
  src/Language/uk/Auth.php
  src/Views/email_activate_show.php
  src/Views/login.php
  src/Views/magic_link_form.php
  src/Views/register.php
Labels: enhancement
