Repository codeigniter4/shield, pull requests merged in 2023-02, with the labels that each got.

#601 Feat: Force password reset
  docs/forcing_password_reset.md
  docs/index.md
  docs/install.md
  src/Config/Auth.php
  src/Config/Registrar.php
  src/Entities/User.php
  src/Filters/ForcePasswordResetFilter.php
  src/Models/UserIdentityModel.php
  src/Models/UserModel.php
  src/Traits/Resettable.php
  tests/Authentication/ForcePasswordResetTest.php
  tests/Unit/UserIdentityModelTest.php
Labels: new feature

#619 refactor: remove `namespace` from language files
  rector.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/sk/Auth.php
  src/Language/tr/Auth.php
Labels: refactor

#620 refactor: replace deprecated Faker property access
  src/Models/LoginModel.php
  src/Models/TokenLoginModel.php
  src/Models/UserIdentityModel.php
  src/Models/UserModel.php
Labels: refactor

#618 Translate pt-BR
  src/Language/pt-BR/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/BrazilianTranslationTest.php
Labels: lang

#621 test: fix ForcePasswordResetTest::forceGlobalPasswordReset()
  src/Models/UserIdentityModel.php
  tests/Authentication/ForcePasswordResetTest.php
Labels: refactor

#623 update lang ~> ID
  src/Language/id/Auth.php
Labels: lang

#622 refactor: UserIdentityModel::update() throws Exception
  src/Models/UserIdentityModel.php
  src/Traits/Resettable.php
Labels: refactor

#580 feat: User activation checks and utility functions.
  docs/authentication.md
  docs/authorization.md
  src/Auth.php
  src/Authentication/Actions/EmailActivator.php
  src/Authentication/Authenticators/Session.php
  src/Controllers/RegisterController.php
  src/Entities/User.php
  src/Filters/SessionAuth.php
  src/Filters/TokenAuth.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/pt-BR/Auth.php
  src/Language/sk/Auth.php
  src/Language/tr/Auth.php
  src/Traits/Activatable.php
  tests/Authentication/Filters/SessionFilterTest.php
  tests/Authentication/Filters/TokenFilterTest.php
  tests/Unit/UserTest.php
Labels: enhancement, breaking change

#625 refactor: use `getIdentity()` for improve action `Email2FA`
  src/Authentication/Actions/Email2FA.php
Labels: refactor

#627 Docs: authorization.md, fixed typo
  docs/authorization.md
Labels: documentation

#626 refactor: change return type to void
  src/Traits/Activatable.php
Labels: refactor

#633 feat: customize name of Shield Tables w/o constant
  docs/customization.md
  docs/install.md
  src/Config/Auth.php
  src/Controllers/RegisterController.php
  src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
  src/Models/BaseModel.php
  src/Models/CheckQueryReturnTrait.php
  src/Models/GroupModel.php
  src/Models/LoginModel.php
  src/Models/PermissionModel.php
  src/Models/RememberModel.php
  src/Models/TokenLoginModel.php
  src/Models/UserIdentityModel.php
  src/Models/UserModel.php
  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
  tests/Authentication/HasAccessTokensTest.php
  tests/Authentication/MagicLinkTest.php
  tests/Authorization/AuthorizableTest.php
  tests/Controllers/ActionsTest.php
  tests/Controllers/LoginTest.php
  tests/Controllers/RegisterTest.php
  tests/Unit/UserModelTest.php
  tests/Unit/UserTest.php
  tests/_support/DatabaseTestCase.php
Labels: enhancement

#637 docs: no need to load `auth_helper`
  docs/authentication.md
Labels: documentation

#642 docs: add `logout` for `force-reset` except
  docs/install.md
Labels: documentation

#651 chore: fix composer-unused version to aviod setup error
  .github/workflows/unused.yml
Labels: github_actions

#647 docs: add note to require filter setting for `last_active`
  src/Config/Auth.php
Labels: documentation
