Repository codeigniter4/shield, pull requests merged in 2023-04, with the labels that each got.

#693 lang: [es] Revision and Update translated to Spanish(Spain) language
  src/Language/es/Auth.php
Labels: lang

#687 docs: add RELEASE.md
  admin/RELEASE.md
Labels: documentation

#696 docs: use `validateData()` instead of `validate()`
  docs/guides/mobile_apps.md
Labels: documentation

#698 docs: update guides/mobile_apps.md
  docs/guides/mobile_apps.md
Labels: documentation

#700 docs: small fixes for install.md
  docs/install.md
Labels: documentation

#703 fix: incorrect base class for exceptions
  src/Exceptions/SecurityException.php
  src/Exceptions/ValidationException.php
Labels: bug

#195 feat: JWT Authenticator
  README.md
  composer.json
  docs/addons/jwt.md
  docs/index.md
  docs/install.md
  mkdocs.yml
  src/Authentication/Authenticators/JWT.php
  src/Authentication/JWT/Adapters/FirebaseAdapter.php
  src/Authentication/JWT/Exceptions/InvalidTokenException.php
  src/Authentication/JWT/JWSAdapterInterface.php
  src/Authentication/JWT/JWSDecoder.php
  src/Authentication/JWT/JWSEncoder.php
  src/Authentication/JWTManager.php
  src/Config/Auth.php
  src/Config/AuthJWT.php
  src/Config/Registrar.php
  src/Config/Services.php
  src/Filters/JWTAuth.php
  src/Language/de/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fa/Auth.php
  src/Language/fr/Auth.php
  src/Language/id/Auth.php
  src/Language/it/Auth.php
  src/Language/ja/Auth.php
  src/Language/pt-BR/Auth.php
  src/Language/pt/Auth.php
  src/Language/sk/Auth.php
  src/Language/sr/Auth.php
  src/Language/sv-SE/Auth.php
  src/Language/tr/Auth.php
  tests/Authentication/Authenticators/JWTAuthenticatorTest.php
  tests/Authentication/Filters/JWTFilterTest.php
  tests/Unit/Authentication/JWT/Adapters/FirebaseAdapaterTest.php
  tests/Unit/Authentication/JWT/JWTManagerTest.php
Labels: new feature

#708 docs: fix jwt.md
  docs/addons/jwt.md
Labels: documentation

#706 docs: change the status code from 422 to 401
  docs/guides/mobile_apps.md
Labels: documentation

#707 lang: Add pt-BR translation for JWT
  src/Language/pt-BR/Auth.php
Labels: lang

#709 lang: update ja
  bin/update-en-comments
  src/Language/ja/Auth.php
Labels: lang

#713 lang: add ukrainian translation
  src/Language/uk/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/UkrainianTranslationTest.php
Labels: lang

#714 docs: improve descriptions on permissions
  docs/authorization.md
  src/Config/AuthGroups.php
Labels: documentation

#718 lang: tr - added translations
  src/Language/tr/Auth.php
Labels: lang

#719 lang: [bg] Add translation for Bulgarian language
  src/Language/bg/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/BulgarianTranslationTest.php
Labels: lang
