Repository codeigniter4/shield, pull requests merged in 2024-08, with the labels that each got.

#1152 lang: [de] Update Auth.php - add missing translation
  src/Language/de/Auth.php
Labels: lang

#1153 test: fix incorrect condition in AbstractTranslationTestCase
  .github/workflows/phpunit-lang.yml
  tests/Language/AbstractTranslationTestCase.php
Labels: testing

#1155 docs: fix filter name for `ChainAuth`
  docs/references/controller_filters.md
Labels: documentation

#1157 lang: [fa] update error message for email verification failure
  src/Language/fa/Auth.php
Labels: lang

#1159 fix: add missing args to `lang('Auth.invalidEmail')`
  src/Authentication/Actions/Email2FA.php
  tests/Controllers/ActionsTest.php
Labels: bug

#1158 lang: [ja] translate updated `invalidEmail`
  src/Language/ja/Auth.php
Labels: lang

#1163 refactor: fix method names with incorrect case
  phpstan-baseline.php
  src/Authentication/Passwords.php
  src/Authentication/Passwords/ValidationRules.php
  src/Filters/TokenAuth.php
Labels: refactor

#1160 fix: `chain` filter does not update `last_active`
  src/Config/Auth.php
  src/Filters/ChainAuth.php
Labels: bug

#1169 fix: Shield ignores `AuthToken::$authenticatorHeader` config
  src/Filters/HmacAuth.php
  src/Filters/TokenAuth.php
Labels: bug

#1174 fix: cannot override `emailer()` function
  src/Helpers/email_helper.php
Labels: bug

#1162 fix: `shield:user create` does not assign a default group
  src/Commands/User.php
  tests/Commands/UserTest.php
Labels: bug

#1164 feat: add -g option to `shield:user create`
  phpstan-baseline.php
  src/Authorization/Traits/Authorizable.php
  src/Commands/User.php
  src/Models/GroupModel.php
  src/Models/UserModel.php
  tests/Commands/UserTest.php
Labels: enhancement

#1178 refactor: [Authorizable Trait] move $matrix outside foreach loop
  src/Authorization/Traits/Authorizable.php
Labels: refactor

#1176 fix: add missing validation for group name to `shield:user addgroup`/`removegroup`
  src/Commands/User.php
  tests/Commands/UserTest.php
Labels: bug

#1185 docs: typo fix in method name
  docs/references/authentication/tokens.md
Labels: docs needed

#1175 fix: confusing lang message `invalidEmail`
  src/Language/ar/Auth.php
  src/Language/bg/Auth.php
  src/Language/cs/Auth.php
  src/Language/en/Auth.php
  src/Language/es/Auth.php
  src/Language/fr/Auth.php
  src/Language/it/Auth.php
  src/Language/lt/Auth.php
  src/Language/nl/Auth.php
  src/Language/pl/Auth.php
  src/Language/pt-BR/Auth.php
  src/Language/pt/Auth.php
  src/Language/ru/Auth.php
  src/Language/sk/Auth.php
  src/Language/sr/Auth.php
  src/Language/sv-SE/Auth.php
  src/Language/tr/Auth.php
  src/Language/uk/Auth.php
Labels: bug

#1188 refactor: remove unneeded Entities\Cast\IntBoolCast
  phpstan-baseline.php
  src/Entities/Cast/IntBoolCast.php
  src/Entities/Entity.php
  src/Entities/Login.php
  src/Entities/User.php
  src/Entities/UserIdentity.php
Labels: refactor
