Repository codeigniter4/shield, pull requests merged in 2024-02, with the labels that each got.

#1015 lang: [cs] Add Czech Translation
  src/Language/cs/Auth.php
  tests/Language/AbstractTranslationTestCase.php
  tests/Language/CzechTranslationTest.php
Labels: lang

#1020 fix: Shield may not send correct HTML mail
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Actions/EmailActivator.php
  src/Controllers/MagicLinkController.php
  src/Helpers/email_helper.php
Labels: bug

#1024 docs: add instruction to change route in extending_controllers.md
  docs/customization/extending_controllers.md
Labels: documentation

#1026 docs: improve descriptions for filters
  docs/quick_start_guide/using_session_auth.md
  docs/references/controller_filters.md
Labels: documentation

#1040 fix: `JWT::loggedIn()` does not remove `Bearer` prefix
  src/Authentication/Authenticators/JWT.php
  src/Filters/JWTAuth.php
  tests/Authentication/Authenticators/JWTAuthenticatorTest.php
Labels: bug

#1041 test: improve tests execution time
  docs/references/testing.md
  phpunit.xml.dist
Labels: refactor, testing

#1042 docs: improve force reset
  docs/user_management/forcing_password_reset.md
Labels: documentation

#1027 refactor: remove hard coded `'Y-m-d H:i:s'`
  src/Authentication/Authenticators/AccessTokens.php
  src/Authentication/Authenticators/HmacSha256.php
  src/Authentication/Authenticators/Session.php
  src/Authorization/Traits/Authorizable.php
  src/Controllers/MagicLinkController.php
  src/Models/LoginModel.php
  src/Models/RememberModel.php
  src/Models/TokenLoginModel.php
  src/Models/UserIdentityModel.php
  src/Models/UserModel.php
  tests/Authentication/MagicLinkTest.php
  tests/Controllers/MagicLinkTest.php
Labels: refactor

#1046 fix: LoginModel cannot use uuid for id column
  src/Models/LoginModel.php
Labels: bug
