Repository codeigniter4/shield, pull requests merged in 2024-04, with the labels that each got.

#1078 fix: Can't create new users via CLI if username is disabled
  phpstan-baseline.php
  src/Commands/User.php
Labels: bug

#1081 refactor: replace empty() by rector
  phpstan-baseline.php
  rector.php
  src/Authentication/Actions/Email2FA.php
  src/Authentication/Authenticators/AccessTokens.php
  src/Authentication/Authenticators/Session.php
  src/Authentication/Passwords.php
  src/Authentication/Passwords/CompositionValidator.php
  src/Authentication/Passwords/NothingPersonalValidator.php
  src/Authentication/Passwords/ValidationRules.php
  src/Authentication/Traits/HasAccessTokens.php
  src/Authorization/Traits/Authorizable.php
  src/Entities/Group.php
  tests/Authentication/Filters/AbstractFilterTestCase.php
Labels: refactor

#1090 test: update for CI 4.5.0
  phpstan-baseline.php
  tests/Controllers/ActionsTest.php
  tests/Unit/AuthRoutesTest.php
Labels: testing

#1088 fix: Call to a member function getErrors() on null in CheckQueryReturnTrait
  src/Models/CheckQueryReturnTrait.php
Labels: bug

#1094 test: fix Registrar for DB Config
  tests/Authentication/HasHmacTokensTest.php
  tests/_support/Config/Registrar.php
Labels: testing

#1095 fix: passing Time to Query Builder in UserModel
  src/Models/UserModel.php
Labels: bug

#1101 docs: remove unneeded "`"
  UPGRADING.md
Labels: documentation

#1109 docs: improve banning users
  docs/references/authentication/authentication.md
  docs/user_management/banning_users.md
  docs/user_management/forcing_password_reset.md
  docs/user_management/managing_users.md
Labels: documentation

#1106 lang: [de] Added missing translations in Auth.php
  src/Language/de/Auth.php
  tests/Language/GermanTranslationTest.php
Labels: lang
