Repository codeigniter4/shield, pull requests merged in 2024-11, with the labels that each got.

#1216 docs: adding note to 'Change Available Permissions'
  docs/quick_start_guide/using_authorization.md
Labels: documentation

#1218 lang: [tr] Language additions
  src/Language/tr/Auth.php
Labels: lang

#1222 refactor: Move property to local variable on usage only in setUp() method in tests
  tests/Authentication/Authenticators/SessionAuthenticatorTest.php
  tests/Authentication/Filters/JWTFilterTest.php
  tests/Authentication/MagicLinkTest.php
  tests/Authorization/AuthorizableTest.php
  tests/Controllers/LoginTest.php
  tests/Controllers/RegisterTest.php
Labels: refactor

#1223 docs: fix trait's name typo in integrating custom view lib
  docs/customization/integrating_custom_view_libs.md
Labels: documentation

#1231 lang: [nl] fix incorrect translation
  src/Language/nl/Auth.php
Labels: lang
