Repository codeigniter4/shield, pull requests merged in 2025-02, with the labels that each got.

#1245 docs: correcting the typo in method name `generateHmacToken`
  docs/references/authentication/hmac.md
Labels: documentation

#1244 docs: fix forcing_password_reset.md link
  docs/user_management/forcing_password_reset.md
Labels: documentation

#1242 fix: CSP error in debugbar
  src/Collectors/Auth.php
Labels: bug

#1196 feat: add ``UserModel::createNewUser()`` and `RegisterController` uses it
  docs/customization/user_provider.md
  src/Controllers/RegisterController.php
  src/Models/UserModel.php
Labels: enhancement

#1246 docs: update copyright for 2025
  LICENSE
  mkdocs.yml
Labels: documentation

#1251 docs: require `activator` in custom actions class name for `register`
  docs/references/authentication/auth_actions.md
  src/Config/Auth.php
Labels: documentation

#1250 refactor: `display()` method to enhance readability and maintainability
  src/Collectors/Auth.php
Labels: refactor

#1256 refactor: improve expiration time calculation using `addSeconds()`
  src/Authentication/Authenticators/Session.php
Labels: refactor
